Add missing `npm ci` before `npx wrangler deploy`
Otherwise this fails:

```console
src/index.ts:3:32 - error TS2307: Cannot find module '@cloudflare/playwright-mcp' or its corresponding type declarations.

3 import { createMcpAgent } from '@cloudflare/playwright-mcp';
```